#!/bin/bash

# --- CONFIGURATION ---
# The config files to symlink
configs=(bash_aliases bash_profile bashrc gitconfig profile tmux.conf vimrc)

# Read apt packages from data file (edit apt-packages.txt directly)
apt_packages=()
if [ -f "$HOME/dotfiles/apt-packages.txt" ]; then
    while IFS= read -r pkg; do
        [[ -z "$pkg" || "$pkg" == \#* ]] && continue
        apt_packages+=("$pkg")
    done < "$HOME/dotfiles/apt-packages.txt"
fi

# Read npm packages from captured list (generated by capture_packages.sh)
npm_packages=()
if [ -f "$HOME/dotfiles/npm-packages.txt" ]; then
    while IFS= read -r pkg; do
        [[ -z "$pkg" || "$pkg" == \#* ]] && continue
        npm_packages+=("$pkg")
    done < "$HOME/dotfiles/npm-packages.txt"
fi

# Read pipx packages from captured list (generated by capture_packages.sh)
pipx_packages=()
if [ -f "$HOME/dotfiles/pipx-packages.txt" ]; then
    while IFS= read -r pkg; do
        [[ -z "$pkg" || "$pkg" == \#* ]] && continue
        pipx_packages+=("$pkg")
    done < "$HOME/dotfiles/pipx-packages.txt"
fi

# The snap packages to install
snap_packages=(ollama) 

# --- EXECUTION ---

# Parse flags
wsl=false
for arg in "$@"; do
    case "$arg" in
        --wsl) wsl=true ;;
    esac
done

# 1. Add NodeSource for the correct Node.js engine (v22+)
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -

# 2. Install apt packages
sudo apt update
sudo apt install -y nodejs "${apt_packages[@]}"

# 3. Configure npm prefix to ~/.local (user-owned, no sudo needed)
mkdir -p "$HOME/.local"
echo "prefix=$HOME/.local" > "$HOME/.npmrc"

# 4. Global NPM installs (to ~/.local, no sudo)
npm install -g "${npm_packages[@]}"

# 5. pipx installs
if command -v pipx &>/dev/null; then
  pipx ensurepath
  for pkg in "${pipx_packages[@]}"; do
    pipx install "$pkg" || echo "  (pipx install failed: $pkg)"
  done
fi

# 6. Snap installs
if command -v snap &>/dev/null; then
  sudo snap install --classic "${snap_packages[@]}" || echo "  (snap install failed)"
fi

# 7. Connect the config files
for file in "${configs[@]}"; do
    ln -sf "$HOME/dotfiles/$file" "$HOME/.$file"
done

# 7a. SSH config (special path: ~/.ssh/config)
mkdir -p "$HOME/.ssh"
ln -sf "$HOME/dotfiles/ssh_config" "$HOME/.ssh/config"

# 8. Bootstrap Flutter SDK
if [ ! -d "$HOME/development/flutter" ]; then
    mkdir -p "$HOME/development"
    git clone https://github.com/flutter/flutter.git -b stable "$HOME/development/flutter"
fi

# 9. Bootstrap Vim-Plug
if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
    curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# 10. Finalize Vim plugins
vim +PlugInstall +qall

# 11. Windows Terminal settings (requires --wsl flag)
if "$wsl" && [ -d "$HOME/dotfiles/windows-terminal" ]; then
    echo "Applying Windows Terminal settings..."
    node "$HOME/dotfiles/windows-terminal/install.js" --apply || echo "  (Windows Terminal install skipped - not available)"
fi

# 12. Pi agent config
if [ -d "$HOME/dotfiles/pi-agent" ]; then
    echo "Installing pi agent config..."
    bash "$HOME/dotfiles/pi-agent/install.sh" --apply || echo "  (pi agent install skipped - not available)"
fi

# 13. VS Code WSL remote settings (requires --wsl flag)
if "$wsl" && [ -d "$HOME/dotfiles/vscode" ]; then
    echo "Installing VS Code WSL remote settings..."
    bash "$HOME/dotfiles/vscode/install.sh" --apply || echo "  (VS Code install skipped - not available)"
fi

echo "Setup Complete. New Node engine, packages, and dotfiles are ready."
