#!/usr/bin/env node
// Extract WSL profile + related settings from the live Windows Terminal config
// Usage: node extract.js [--profile <guid>]
//
// If --profile is omitted, it detects which profile you're currently running
// under via the WT_PROFILE_ID environment variable. If that's not set either,
// it falls back to the profile saved in settings.json.

import fs from "node:fs";
import path from "node:path";

const getWtConfigPath = () => {
  if (process.env.WT_CONFIG) return process.env.WT_CONFIG;
  // Windows
  if (process.env.USERPROFILE) {
    return path.join(
      process.env.USERPROFILE,
      "AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json",
    );
  }
  // WSL — search each user directory for the config file
  const wslUsers = path.join("/mnt/c/Users/");
  if (fs.existsSync(wslUsers)) {
    const subPath =
      "AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json";
    for (const user of fs.readdirSync(wslUsers)) {
      const candidate = path.join(wslUsers, user, subPath);
      if (fs.existsSync(candidate)) return candidate;
    }
  }
  return null;
};

const WT_CONFIG = getWtConfigPath();

const SAVED_CONFIG = path.join(import.meta.dirname, "settings.json");

// --- CLI args ---
const args = process.argv.slice(2);
const profileFlagIdx = args.indexOf("--profile");
let targetGuid = args[profileFlagIdx + 1] ?? process.env.WT_PROFILE_ID;

// Strip braces for matching
const normalizeGuid = (g) => (g ?? "").replace(/[{}]/g, "");

// --- Read live config (strip JSON5 comments) ---
let raw;
try {
  raw = fs.readFileSync(WT_CONFIG, "utf-8");
} catch {
  console.error(`Cannot read ${WT_CONFIG}. Are you on Windows / WSL?`);
  process.exit(1);
}

// Strip JSON5: comments outside strings, trailing commas
const stripJson5 = (src) => {
  let out = "";
  let inString = false;
  let escape = false;
  for (let i = 0; i < src.length; i++) {
    const ch = src[i];
    if (inString) {
      out += ch;
      if (escape) { escape = false; continue; }
      if (ch === "\\") escape = true;
      if (ch === '"') inString = false;
      continue;
    }
    // Not in string
    if (ch === '"') { inString = true; out += ch; continue; }
    if (ch === "/" && src[i + 1] === "/") {
      // skip to end of line
      i += 2;
      while (i < src.length && src[i] !== "\n") i++;
      out += "\n";
      continue;
    }
    out += ch;
  }
  // Remove trailing commas
  return out.replace(/,\s*([}\]])/g, "$1");
};

const stripped = stripJson5(raw);

let wt;
try {
  wt = JSON.parse(stripped);
} catch (e) {
  console.error(`Failed to parse settings.json: ${e.message}`);
  process.exit(1);
}

// --- Read saved config for fallback GUID ---
let savedGuid = null;
try {
  const saved = JSON.parse(fs.readFileSync(SAVED_CONFIG, "utf-8"));
  savedGuid = saved.wslProfile?.guid;
} catch {
  // first run, no saved config yet
}

if (!targetGuid) {
  targetGuid = savedGuid;
  console.log(
    `No --profile and no WT_PROFILE_ID. Falling back to saved profile: ${targetGuid}`,
  );
}
if (!targetGuid) {
  console.error(
    "Cannot determine profile GUID. Pass --profile <guid> or run from a Windows Terminal session.",
  );
  process.exit(1);
}

const wasExplicit = args[profileFlagIdx + 1] !== undefined;
targetGuid = normalizeGuid(targetGuid);

// Warn if auto-detected GUID differs from saved
if (
  !wasExplicit &&
  savedGuid &&
  normalizeGuid(savedGuid) !== targetGuid
) {
  console.warn(
    `WT_PROFILE_ID (${targetGuid}) differs from saved profile (${savedGuid}).`,
  );
  console.warn(
    "This may be the auto-generated distro profile. Use --profile to pick explicitly.",
  );
}

// --- Find the profile ---
const profiles = wt.profiles?.list ?? [];
const profile = profiles.find(
  (p) => normalizeGuid(p.guid) === targetGuid,
);

if (!profile) {
  console.error(
    `Profile with GUID ${targetGuid} not found in Windows Terminal settings.`,
  );
  console.log("Available profiles:");
  for (const p of profiles) {
    console.log(`  ${p.guid}  ${p.name}`);
  }
  process.exit(1);
}

console.log(`Extracting profile: ${profile.name} (${profile.guid})`);

// Guard: refuse to overwrite saved config with an auto-generated profile
const isAutoGenerated =
  profile.source !== undefined &&
  !profile.colorScheme &&
  !profile.font &&
  !profile.cursorShape &&
  !profile.tabTitle;

if (isAutoGenerated && !wasExplicit && savedGuid) {
  console.error(
    `\nProfile "${profile.name}" looks auto-generated (no custom settings).`,
  );
  console.error(
    `This will overwrite your saved "${JSON.parse(fs.readFileSync(SAVED_CONFIG, "utf-8")).wslProfile.name}" config.`,
  );
  console.error(
    `Aborting. Re-run with --profile to explicitly select a profile.`,
  );
  process.exit(1);
}

// --- Extract color schemes referenced by this profile ---
const allSchemes = wt.schemes ?? [];
const schemeName = profile.colorScheme;
const referencedSchemes = schemeName
  ? allSchemes.filter((s) => s.name === schemeName)
  : [];

// --- Build output ---
const output = {
  wslProfile: {
    guid: profile.guid,
    name: profile.name,
    commandline: profile.commandline,
    colorScheme: profile.colorScheme ?? null,
    cursorShape: profile.cursorShape ?? null,
    font: profile.font ?? null,
    icon: profile.icon ?? null,
    startingDirectory: profile.startingDirectory ?? null,
    tabTitle: profile.tabTitle ?? null,
  },
  colorSchemes: referencedSchemes,
  globalSettings: {
    actions: wt.actions ?? [],
    keybindings: wt.keybindings ?? [],
    copyFormatting: wt.copyFormatting ?? "none",
    copyOnSelect: wt.copyOnSelect ?? false,
  },
};

fs.writeFileSync(SAVED_CONFIG, JSON.stringify(output, null, 2) + "\n");
console.log(`Saved to ${SAVED_CONFIG}`);
console.log(
  `  Profile: ${output.wslProfile.name} (${output.wslProfile.guid})`,
);
console.log(`  Color scheme: ${output.wslProfile.colorScheme ?? "(default)"}`);
console.log(
  `  Global actions: ${(output.globalSettings.actions ?? []).length}`,
);
console.log(
  `  Keybindings: ${(output.globalSettings.keybindings ?? []).length}`,
);
